const pasatiempos = [
    "Leer libros de fantasía y misterio",
    "Hacer caminatas al aire libre",
    "Jugar videojuegos",
    "Cocinar recetas nuevas",
    "Practicar yoga",
    "Ver series y películas",
    "Hacer jardinería",
    "Tocar un instrumento musical",
    "Pintar o dibujar",
    "Escribir cuentos o poesía",
    "Salir a correr o trotar",
    "Hacer fotografía",
    "Coleccionar monedas o sellos",
    "Andar en bicicleta",
    "Explorar cafés o restaurantes nuevos",
    "Hacer manualidades o bricolaje",
    "Bailar en casa o tomar clases de baile",
    "Hacer meditación",
    "Armar rompecabezas o jugar juegos de mesa",
    "Explorar senderos de montaña",
    "Aprender un nuevo idioma",
    "Hacer camping o actividades al aire libre",
    "Asistir a conciertos o eventos culturales",
    "Hacer modelismo o ensamblar maquetas",
    "Correr maratones o participar en eventos deportivos",
    "Ir de pesca",
    "Viajar y explorar nuevos lugares",
    "Participar en clubes de lectura",
    "Aprender técnicas de fotografía con drones",
    "Entrenar mascotas o aprender sobre comportamiento animal",
	"Practicar natación o deportes acuáticos",
    "Hacer repostería y experimentar con postres creativos",
    "Jugar ajedrez o aprender estrategias avanzadas",
    "Explorar museos y galerías de arte",
    "Participar en competencias de trivia o quiz online",
    "Hacer voluntariado en organizaciones locales",
    "Cultivar hierbas aromáticas o vegetales en casa",
    "Explorar parques nacionales o reservas naturales",
    "Aprender a bailar estilos como salsa, tango o bachata",
    "Crear contenido para redes sociales o blogs personales",
    "Disfrutar de la astronomía y observar las estrellas",
    "Hacer entrenamiento funcional o calistenia",
    "Explorar la escritura de guiones o narrativas visuales",
    "Construir muebles pequeños o proyectos de carpintería",
    "Descubrir técnicas de bordado, tejido o crochet",
    "Hacer senderismo nocturno y observar la naturaleza al anochecer",
    "Participar en talleres de teatro o actuación",
    "Coleccionar vinilos, cómics o figuras de acción",
    "Aprender técnicas avanzadas de cocina internacional",
    "Participar en eventos de cosplay o diseño de disfraces",
    "Crear música digital utilizando software especializado",
    "Aprender a mezclar como DJ amateur",
    "Construir y volar cometas",
    "Hacer carreras de drones recreativas",
    "Explorar la apicultura y el cultivo de miel artesanal",
    "Probar recetas de coctelería y aprender sobre mixología",
    "Hacer origami y explorar formas complejas",
    "Descubrir la caligrafía artística o el lettering",
    "Aprender sobre jardinería vertical o cultivo hidropónico",
    "Hacer maratones de lectura de libros clásicos",
    "Escribir en un diario para reflexionar sobre el día a día",
    "Organizar viajes temáticos o escapadas de fin de semana",
    "Participar en ligas de deportes amateurs como fútbol o baloncesto",
    "Hacer experimentos científicos caseros por diversión",
    "Aprender sobre fotografía analógica y revelar en cuarto oscuro",
    "Practicar tiro con arco en clubes locales",
    "Diseñar y jugar juegos de rol de mesa como Dungeons & Dragons",
    "Descubrir y probar nuevos tipos de té o café",
    "Aprender a reparar bicicletas o automóviles",
    "Participar en maratones virtuales o retos deportivos",
    "Explorar recetas tradicionales de diferentes culturas",
    "Tener una colección de plantas exóticas o suculentas",
    "Practicar deportes de aventura como escalada o rafting",
    "Hacer un curso de cerámica o alfarería",
    "Explorar técnicas de maquillaje artístico",
    "Observar aves y aprender sobre especies locales",
    "Aprender sobre historia a través de documentales y libros",
    "Crear proyectos DIY para decorar espacios en casa",
    "Explorar juegos de realidad virtual en consolas o PCs",
    "Participar en actividades de mindfulness como mandalas o journaling"
];


module.exports = { pasatiempos };