const tareas = [
    "Hacer la lista de compras para la semana",
    "Enviar el correo con la propuesta del proyecto",
    "Ordenar el escritorio de trabajo",
    "Pagar las facturas del mes",
    "Llamar al médico para agendar una cita",
    "Preparar la presentación para la reunión del jueves",
    "Revisar los documentos del contrato",
    "Lavar el auto",
    "Planificar las vacaciones familiares",
    "Estudiar para el examen de certificación",
    "Comprar un regalo para el cumpleaños de un amigo",
    "Actualizar el currículum vitae",
    "Llevar las prendas a la tintorería",
    "Terminar de leer el libro pendiente",
    "Inscribirse a un curso en línea",
    "Realizar ejercicio al menos tres veces esta semana",
    "Hacer limpieza profunda en la cocina",
    "Enviar los documentos para el trámite administrativo",
    "Instalar las actualizaciones en la computadora",
    "Ir al supermercado por los productos que faltan",
    "Escribir un artículo para el blog personal",
    "Revisar el presupuesto mensual",
    "Sacar a pasear al perro",
    "Hacer backup de los archivos importantes",
    "Arreglar el grifo que gotea en el baño",
    "Renovar la suscripción al gimnasio",
    "Configurar la nueva impresora",
    "Planificar una cena con amigos",
    "Responder los mensajes pendientes en el correo",
    "Hacer una lista de objetivos para el próximo mes",
	"Organizar y limpiar el espacio de trabajo en casa",
    "Preparar una presentación para una reunión importante",
    "Establecer un presupuesto mensual y analizar gastos",
    "Planificar un menú semanal y hacer la lista de compras",
    "Actualizar el currículum vitae y perfil de LinkedIn",
    "Responder correos electrónicos pendientes",
    "Configurar un calendario con recordatorios para tareas futuras",
    "Redactar un informe detallado sobre los logros del mes",
    "Organizar archivos y carpetas en el computador",
    "Capacitarse en una nueva herramienta digital",
    "Revisar y renovar documentos legales o contratos",
    "Planear y coordinar una actividad de equipo",
    "Desarrollar un esquema para un proyecto personal",
    "Investigar cursos en línea relacionados con el área de interés",
    "Revisar y corregir documentos antes de entregarlos",
    "Actualizar la lista de contactos profesionales",
    "Revisar y priorizar tareas pendientes de la semana",
    "Crear un plan de acción para alcanzar una meta específica",
    "Escribir un borrador para un artículo o blog personal",
    "Realizar una auditoría rápida de redes sociales personales",
    "Configurar y optimizar aplicaciones en dispositivos móviles",
    "Revisar y mejorar la seguridad de contraseñas y cuentas en línea",
    "Hacer una sesión de brainstorming para un proyecto creativo",
    "Diseñar una estrategia de marketing para un producto o idea",
    "Asistir a una sesión de mentoría o coaching",
    "Resolver problemas técnicos menores en el hogar",
    "Leer y tomar notas sobre artículos académicos o técnicos",
    "Preparar materiales para una próxima reunión o presentación",
    "Practicar habilidades de oratoria o presentaciones públicas",
    "Recopilar datos y hacer análisis para un reporte",
    "Participar en sesiones de retroalimentación o reuniones de equipo",
    "Realizar una encuesta para recopilar opiniones sobre un proyecto",
    "Investigar nuevas tendencias o avances en el campo profesional",
    "Documentar procedimientos para futuros proyectos",
    "Configurar un sistema de almacenamiento en la nube",
    "Diseñar un plan de capacitación para compañeros o empleados",
    "Desarrollar un prototipo para una idea innovadora",
    "Elaborar una lista de objetivos personales y profesionales",
    "Crear y mantener un diario de productividad",
    "Participar en un taller o evento de networking",
    "Actualizar y organizar una base de datos personal o profesional",
    "Crear gráficos o visualizaciones de datos para una presentación",
    "Llevar a cabo reuniones individuales con colegas o colaboradores",
    "Investigar sobre políticas o reglamentos relevantes al trabajo",
    "Planificar un evento social o profesional",
    "Probar nuevas aplicaciones o herramientas para la gestión del tiempo",
    "Desarrollar un sistema de recompensas para motivación personal",
    "Crear una guía o manual para uso interno del equipo",
    "Coordinar la logística de un evento próximo",
    "Escribir un resumen ejecutivo para una propuesta importante"
];


module.exports = { tareas }